version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commune
    volumes:
      - ./docker/mysql-conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  # nginx:
  #   image: nginx:1.13.5-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     # - ./web/app/src/public:/var/data/static
