version: '2'
services:
  db:
    build: docker/mysql
    volumes:
      - ./docker/mysql/mysql-init.sql:/commune-entry.sql
      - ~/docker/data/mysql:/var/lib/mysql
      # - ./docker/mysql-conf/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    command: --init-file /commune-entry.sql --innodb-use-native-aio=0
    restart: always
  # nginx:
  #   image: nginx:1.13.5-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     # - ./web/app/src/public:/var/data/static
