version: '2'
services:
  db:
    image: groonga/mroonga:mysql5722_mroonga803
    volumes:
      - ./docker/mysql/mysql-init.sql:/commune-entry.sql
      - ~/docker/data/mysql:/var/lib/mysql
      # - ./docker/mysql-conf/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    command:
      "--init-file /commune-entry.sql \
       --innodb_buffer_pool_size=2G \
       --innodb-use-native-aio=0 \
       --skip-name-resolve"
    restart: always
  # nginx:
  #   image: nginx:1.13.5-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     # - ./web/app/src/public:/var/data/static
