version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commune
    volumes:
      - ./docker/mysql-conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
